### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by Guard13007** [Guard13007/No-Pico-s-Sky#1]
- [ ] tgt in capital letters
- [ ] hovered system in top left instead of relative to system
- [ ] fuel range circle and proper calculations for adjacent sector jumps!
- [ ] start generating system elements, display list on galaxy map
- [ ] start generating ships

**Comment by Guard13007** [comment]
Note: tgt on top, alternates with hover info, make a sysinfo function to generate the quick info about a system

**Comment by Guard13007** [comment]
- [ ] Double check these systems.
